replicaCount: 2

image:
  repository: ghcr.io/setavitiki/cloudnative-ecommerce/auth-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 4000

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}

env:
  JWT_SECRET: "production-jwt-secret"
